GRID_PADDING = 5
Y_PADDING_FACTOR = 50
HEADER_HEIGHT = 50
BUTTON_PX_WIDTH = 36
BUTTON_PX_HEIGHT = 31
GRID_SIZE = 6
WIDTH = (BUTTON_PX_WIDTH*GRID_SIZE)
HEIGHT = (BUTTON_PX_HEIGHT*GRID_SIZE) + Y_PADDING_FACTOR


MENU_SCREEN_SIZE = "280x320"

IN_GAME_SCREEN_SIZE = f"{WIDTH + (GRID_PADDING*2)}x{HEIGHT + GRID_PADDING}"
IN_GAME_HEADER_WIDTH = WIDTH + (GRID_PADDING*2)
IN_GAME_HEADER_HEIGHT = HEADER_HEIGHT
IN_GAME_BODY_WIDTH = WIDTH + (GRID_PADDING*2)
IN_GAME_BODY_HEIGHT = HEIGHT - Y_PADDING_FACTOR + (GRID_PADDING*2)

IN_GAME_RESTART_BUTTON_W = 34
IN_GAME_RESTART_BUTTON_X = (IN_GAME_HEADER_WIDTH / 2) - (IN_GAME_RESTART_BUTTON_W / 2)

IN_GAME_EXIT_BUTTON_W = 48
IN_GAME_EXIT_BUTTON_PADDING_RIGHT = 7
IN_GAME_EXIT_BUTTON_X = IN_GAME_HEADER_WIDTH - (IN_GAME_EXIT_BUTTON_W + IN_GAME_EXIT_BUTTON_PADDING_RIGHT)



CELL_COUNT = GRID_SIZE ** 2
MINE_COUNT = CELL_COUNT // 4